version: "3.8"

services:
  portainer:
    restart: always
    image: portainer/portainer-ce:latest
    # ports:
    #   - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: portainer-data
        target: /data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN_NAME}`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
  
  prometheus:
    image: prom/prometheus
    # ports:
    #   - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - type: volume
        source: prometheus-data
        target: /prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN_NAME}`)'
      - "traefik.http.routers.prometheus.middlewares=dapci-auth@file"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"


  traefik:
    image: traefik:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/:/etc/traefik/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik.middlewares=dapci-auth@file"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  whoami:
    image: traefik/whoami
    restart: unless-stopped
    # ports:
    #   - "2002:2002"
    command:
      - --port=2002
      - --name="I am DaPCI"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN_NAME}`)"
      - "traefik.http.services.whoami.loadbalancer.server.port=2002"

volumes:
  portainer-data:

  prometheus-data:
