providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

  file:
    filename: /etc/traefik/file-config.yml

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

  metrics:
    address: ":8082"

api:
  dashboard: true
  debug: true
  insecure: true

metrics:
  prometheus:
    entryPoint: metrics
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
